### PR TITLE
In doc generation, pass --case-insensitive-filenames and correct cleanup

### PR DESCRIPTION
**Pull request by nordlow**
Also uses `rm` flag `-f` in `makedocs.sh`.

### CODE REVIEW

**Comment by adamdruppe** [comment]
What does that script do?

```
#!/bin/bash
set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR=$SCRIPT_DIR
SOURCE_DIR=${PROJECT_DIR}/source/nanomsg
echo generating documents for "${PROJECT_DIR}"
mkdir -p docs
[ -e tmp ] && rm -r tmp # looks like this might be where it is failing
mkdir tmp
cd tmp
git clone https://github.com/adamdruppe/adrdox
cp "${PROJECT_DIR}"/.skeleton.html adrdox/skeleton.html
￼mkdir -p "${PROJECT_DIR}"/docs/examples
￼cd adrdox
￼make
￼./doc2 -i "${SOURCE_DIR}"
￼./doc2 --case-insensitive-filenames -i "${SOURCE_DIR}"
￼mv generated-docs/* "${PROJECT_DIR}"/docs
￼./doc2 -i "${PROJECT_DIR}"/examples
￼./doc2 --case-insensitive-filenames -i "${PROJECT_DIR}"/examples
￼mv generated-docs/* "${PROJECT_DIR}"/docs/examples
￼cp "${PROJECT_DIR}"/docs/nanomsg.html "${PROJECT_DIR}"/docs/index.html
￼cd "${PROJECT_DIR}"
rm -r tmp
echo succeeded - docs generated
```

There's some git files in there marked read only that it cannot delete. You could try `rm -rf tmp` on that line to force it to delete the read only files too.

**Comment by nordlow** [comment]
> What does that script do?
> 
> ```
> #!/bin/bash
> set -euo pipefail
> SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
> PROJECT_DIR=$SCRIPT_DIR
> SOURCE_DIR=${PROJECT_DIR}/source/nanomsg
> echo generating documents for "${PROJECT_DIR}"
> mkdir -p docs
> [ -e tmp ] && rm -r tmp # looks like this might be where it is failing
> mkdir tmp
> cd tmp
> git clone https://github.com/adamdruppe/adrdox
> cp "${PROJECT_DIR}"/.skeleton.html adrdox/skeleton.html
> ￼mkdir -p "${PROJECT_DIR}"/docs/examples
> ￼cd adrdox
> ￼make
> ￼./doc2 -i "${SOURCE_DIR}"
> ￼./doc2 --case-insensitive-filenames -i "${SOURCE_DIR}"
> ￼mv generated-docs/* "${PROJECT_DIR}"/docs
> ￼./doc2 -i "${PROJECT_DIR}"/examples
> ￼./doc2 --case-insensitive-filenames -i "${PROJECT_DIR}"/examples
> ￼mv generated-docs/* "${PROJECT_DIR}"/docs/examples
> ￼cp "${PROJECT_DIR}"/docs/nanomsg.html "${PROJECT_DIR}"/docs/index.html
> ￼cd "${PROJECT_DIR}"
> rm -r tmp
> echo succeeded - docs generated
> ```
> 
> There's some git files in there marked read only that it cannot delete. You could try `rm -rf tmp` on that line to force it to delete the read only files too.

Thanks. I've adjusted the script and update the docs accordingly.

**Comment by nordlow** [comment]
Ready now, @atilaneves.

**Comment by atilaneves** [comment]
Shouldn't the script change be one MR, and the result of running it be another? I can't even find it in the enormous diff.

**Comment by kinke** [comment]
For some reason, this commit includes a revert of https://github.com/symmetryinvestments/nanomsg-wrapper/commit/78862290f89b3a49f5b07e29704fed4bd8767911.

**Comment by nordlow** [comment]
> For some reason, this commit includes a revert of [7886229](https://github.com/symmetryinvestments/nanomsg-wrapper/commit/78862290f89b3a49f5b07e29704fed4bd8767911).

Fixed.

**Comment by nordlow** [comment]
> Shouldn't the script change be one MR, and the result of running it be another? I can't even find it in the enormous diff.

PR adjusted to only contain adjustment of `makedocs.sh`. Ready now.

**Comment by nordlow** [comment]
Made some further robustifications to `makedocs.sh` with regards to avoiding global state.

**Review by atilaneves — APPROVED** [review]

**Comment by nordlow** [comment]
Follow up at https://github.com/symmetryinvestments/nanomsg-wrapper/pull/19.

**Pull request merged**
