### PR TITLE
Remove docs directory as some the files under docs gets modified when cloned to case-insensitive filesystems (Windows and MacOS)

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by nordlow** [comment]
Ping, @atilaneves.

**Comment by atilaneves** [comment]
Wouldn't the fix be to change the file names instead? What do you mean that they get modified though?

**Comment by nordlow** [comment]
> Wouldn't the fix be to change the file names instead? What do you mean that they get modified though?

Some files in the docs folder have the same name if you discard casing. On Windows and Mac OS when these files are updated may result in the last write overwriting the lowercased file with the uppercased content...crazyily stupid behavior.

**Comment by nordlow** [comment]
> > Wouldn't the fix be to change the file names instead? What do you mean that they get modified though?
> 
> Some files in the docs folder have the same name if you discard casing. On Windows and Mac OS when these files are updated may result in the last write overwriting the lowercased file with the uppercased content...crazyily stupid behavior.

The same happened with iopipe version 0.2.4. This was the reason why 0.2.5 is preferred from a CI perspective.

**Comment by nordlow** [comment]
Closing in favor of https://github.com/symmetryinvestments/nanomsg-wrapper/pull/18.

**Pull request closed without merging**
